name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test (Ruby ${{ matrix.ruby }})
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.4"
          - "4.0"
    continue-on-error: ${{ matrix.ruby == '4.0' }}

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test

  lint:
    runs-on: ubuntu-latest
    name: Lint (standardrb)
    permissions:
      checks: write
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: standardrb/standard-ruby-action@v1
        with:
          ruby-version: "3.4"
          autofix: false
